# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-30 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('video_html_code', models.CharField(default=None, max_length=200)),
                ('pub_date', models.DateTimeField()),
                ('youtube_id', models.CharField(blank=True, default=None, max_length=11, null=True)),
            ],
        ),
    ]
