# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-16 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_html_code',
            field=models.CharField(default=None, max_length=200, verbose_name='html-\u043a\u043e\u0434'),
        ),
    ]
