# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-18 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20160816_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_section',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
    ]
