# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-19 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_video_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='\u0440\u0430\u0437\u0434\u0435\u043b \u0432\u0438\u0434\u0435\u043e')),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_section',
        ),
        migrations.AddField(
            model_name='videosection',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video'),
        ),
    ]
