# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-19 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20161119_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosection',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='VideoSection',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='videos.VideoSection'),
        ),
    ]
