# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-20 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20161119_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='VideoSection',
        ),
        migrations.AddField(
            model_name='video',
            name='video_section',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='videos.VideoSection'),
        ),
    ]
