# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-13 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_new_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image_bg_color',
            field=models.CharField(default='#000000', max_length=7, validators=[news.models.image_bg_validator]),
        ),
    ]
