# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-16 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_new_image_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='title2',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique_for_date='posted', verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
