# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-16 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_new_title2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image_bg_color',
            field=models.CharField(default='#fff', max_length=7, validators=[news.models.image_bg_validator]),
        ),
    ]
