# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-18 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test18_26',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests18_26', models.TextField(unique=True)),
            ],
        ),
    ]
