# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-18 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test18_26',
            new_name='Tests18_26',
        ),
    ]
