# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-13 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='res_numbers',
        ),
    ]
