# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-24 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0002_auto_20160818_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests18_26',
            name='answer',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='tests18_26',
            name='tests18_26',
            field=models.TextField(),
        ),
    ]
