# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-13 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0002_remove_useranswer_res_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='res_numbers',
            field=models.CharField(blank=True, default=None, max_length=9, null=True),
        ),
    ]
