# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-19 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0004_auto_20161013_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests18_26',
            name='tests18_26',
            field=models.TextField(verbose_name='C\u043a\u043e\u043f\u0438\u0440\u0443\u0439\u0442\u0435 \u0432 \u044d\u0442\u043e \u043f\u043e\u043b\u0435 \u0442\u0435\u043a\u0441\u0442 \u0442\u0435\u0441\u0442\u0430 c \u0441\u0430\u0439\u0442\u0430 fipi.ru:'),
        ),
    ]
