# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-24 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0004_auto_20160824_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests18_26',
            name='answer',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
