# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-24 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0005_auto_20160824_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests18_26',
            name='answer',
        ),
    ]
