# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-25 13:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0007_tests18_26_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tests18_26',
            name='answer',
        ),
        migrations.AddField(
            model_name='tests18_26',
            name='pub_data',
            field=models.DateTimeField(default=datetime.date(2016, 8, 25), verbose_name='\u0434\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438'),
        ),
        migrations.AddField(
            model_name='answer',
            name='tests18_26',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oge.Tests18_26'),
        ),
    ]
