# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-25 13:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0009_auto_20160825_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests18_26',
            name='pub_data',
            field=models.DateTimeField(default=datetime.date(2016, 8, 25), verbose_name='\u0434\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438'),
        ),
    ]
