# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-26 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0011_auto_20160825_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests18_26',
            name='splited_tests18_26',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
