# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-30 11:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oge', '0012_tests18_26_splited_tests18_26'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('answer_pub_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0434\u0430\u0442\u0430 \u043e\u0442\u0432\u0435\u0442\u0430')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='tests18_26',
        ),
        migrations.AddField(
            model_name='tests18_26',
            name='answer',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='tests18_26',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oge.Tests18_26'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
