# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-10 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('post', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0438 \u0434\u0430\u0442\u0430 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438')),
                ('stuffFile', models.FileField(blank=True, default=None, null=True, upload_to='stuff_pdf/%Y/%m', verbose_name='\u0424\u0430\u0439\u043b \u0441 \u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u0430\u043c\u0438')),
            ],
        ),
    ]
