# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-11 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0003_auto_20171010_2042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stuff',
            new_name='MumStuff',
        ),
        migrations.AlterModelOptions(
            name='mumstuff',
            options={'ordering': ['-posted'], 'verbose_name': '\u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b \u0434\u043b\u044f \u043c\u0430\u043c', 'verbose_name_plural': '\u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u044b \u0434\u043b\u044f \u043c\u0430\u043c'},
        ),
        migrations.RenameField(
            model_name='mumstuff',
            old_name='post',
            new_name='posted',
        ),
    ]
