# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-11 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0004_auto_20171011_1245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MumStuff',
            new_name='MomStuff',
        ),
    ]
