# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0005_auto_20171011_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momstuff',
            name='stuffFile',
            field=models.FileField(null=True, upload_to='stuff_pdf/%Y/%m', verbose_name='\u0424\u0430\u0439\u043b \u0441 \u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u0430\u043c\u0438'),
        ),
        migrations.AlterField(
            model_name='momstuff',
            name='title',
            field=models.CharField(max_length=80, unique_for_date='posted', verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
