# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-09-19 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import newsletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20170919_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='check_in_date',
            field=models.CharField(choices=[('1', '22\u201324.09.17'), ('2', '29.09\u201301.10.17'), ('3', '6\u20138.10.17'), ('4', '27\u201329.10.17'), ('5', '24\u201326.11.17')], default='5', max_length=15, verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0434\u0430\u0442\u0443 \u0437\u0430\u0435\u0437\u0434\u0430:'),
        ),
        migrations.AlterField(
            model_name='join',
            name='tel',
            field=models.CharField(default='1234567890', max_length=16, validators=[newsletter.models.tel_validator]),
        ),
    ]
