# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-11 09:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20170919_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='birth_data',
            field=models.DateField(default=datetime.date(2017, 10, 11)),
        ),
    ]
