# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-16 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20171011_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='birth_data',
            field=models.DateField(),
        ),
    ]
