# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-18 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('event_data', models.DateTimeField(verbose_name='when event happening')),
            ],
        ),
        migrations.CreateModel(
            name='Fotofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnails_width', models.PositiveIntegerField()),
                ('thumbnails_height', models.PositiveIntegerField()),
                ('foto', models.ImageField(height_field='thumbnails_height', upload_to='fotos/thumbnails/%Y/%m/%d', width_field='thumbnails_width')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
            ],
        ),
    ]
