# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-18 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotofile',
            name='thumbnails_height',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='fotofile',
            name='thumbnails_width',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
