# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-22 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160418_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotogalery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnails_width', models.PositiveSmallIntegerField()),
                ('thumbnails_height', models.PositiveSmallIntegerField()),
                ('foto', models.ImageField(height_field='thumbnails_height', upload_to='/thumbnails/%Y/%m/%d', width_field='thumbnails_width')),
            ],
        ),
        migrations.RemoveField(
            model_name='fotofile',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(max_length=200, verbose_name='what event?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_data',
            field=models.DateTimeField(verbose_name='data event happening'),
        ),
        migrations.DeleteModel(
            name='Fotofile',
        ),
        migrations.AddField(
            model_name='fotogalery',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event'),
        ),
    ]
