# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-19 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160630_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(upload_to='fotos/%Y/%m', verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0444\u043e\u0442\u043e\u0444\u0430\u0439\u043b'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto_1x',
            field=models.ImageField(default=None, null=True, upload_to='fotos/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto_2x',
            field=models.ImageField(default=None, null=True, upload_to='fotos/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto_3x',
            field=models.ImageField(default=None, null=True, upload_to='fotos/%Y/%m'),
        ),
    ]
