# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-22 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160422_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotogalery',
            name='thumbnails_height',
        ),
        migrations.RemoveField(
            model_name='fotogalery',
            name='thumbnails_width',
        ),
        migrations.AddField(
            model_name='fotogalery',
            name='name',
            field=models.CharField(default='foto', max_length=200, verbose_name='the title of the foto'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_data',
            field=models.DateField(verbose_name='data event happening'),
        ),
        migrations.AlterField(
            model_name='fotogalery',
            name='foto',
            field=models.ImageField(upload_to='fotos/thumbnails/%Y/%m/%d'),
        ),
    ]
