# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-09-15 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baner', '0002_auto_20170915_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baner',
            name='jumbotron_bg_img',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
